/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uis;

import controladores.AlumnoDTO;
import grillas.GrillaAlumnos;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import objetos.Alumno;
import static uis.PreABMGrado.gradosDTO;
import static uis.Principal.grados;

/**
 *
 * @author ariel
 */
public class PreABMAlumno extends javax.swing.JInternalFrame {

    /**
     * Creates new form PreABMAlumno
     */
    
    static AlumnoDTO alumnosDTO = new AlumnoDTO();
    static ArrayList<Alumno> alumnos = new ArrayList<>();

    public PreABMAlumno() {
        grados = gradosDTO.extraerTodo();
        initComponents();
        actualizarGrilla();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grillaCargos1 = new grillas.GrillaCargos();
        grillaAlumnos1 = new grillas.GrillaAlumnos();
        jPanel1 = new javax.swing.JPanel();
        jbCerrar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();
        jbBuscarMatricula = new javax.swing.JButton();
        jtfBuscarMatricula = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtAlumnos = new javax.swing.JTable();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jbCerrar.setText("Cerrar");
        jbCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrarActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jbBuscarMatricula.setText("Buscar por matrícula");
        jbBuscarMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarMatriculaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jbNuevo)
                .addGap(18, 18, 18)
                .addComponent(jbModificar)
                .addGap(18, 18, 18)
                .addComponent(jbEliminar)
                .addGap(179, 179, 179)
                .addComponent(jbBuscarMatricula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfBuscarMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jbCerrar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbNuevo)
                        .addComponent(jbModificar)
                        .addComponent(jbEliminar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbCerrar)
                            .addComponent(jbBuscarMatricula)
                            .addComponent(jtfBuscarMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jtAlumnos.setModel(grillaAlumnos1);
        jScrollPane2.setViewportView(jtAlumnos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("Comandos");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrarActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jbCerrarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        if (jtAlumnos.getSelectedRow() == -1){JOptionPane.showMessageDialog(null, "Seleccione alumno");}
        else{
        alumnos = alumnosDTO.extraerTodo();
        alumnosDTO.eliminar(alumnos.get(jtAlumnos.getSelectedRow()).getId());
        actualizarGrilla();}
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        AltaAlumno jpAltaAlumno = new AltaAlumno();      
        JFrame jfAltaAlumno = new JFrame();
        jfAltaAlumno.add(jpAltaAlumno, BorderLayout.CENTER);
        jfAltaAlumno.pack();
        jfAltaAlumno.setLocationRelativeTo(null);
        jfAltaAlumno.setVisible(true);
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        if (jtAlumnos.getSelectedRow() == -1){JOptionPane.showMessageDialog(null, "Seleccione alumno");}
        else{
        alumnos = alumnosDTO.extraerTodo();
        ModificarAlumno jpModificarAlumno = new ModificarAlumno(alumnos.get(jtAlumnos.getSelectedRow()));  
        JFrame jfModificarAlumno = new JFrame();
        jfModificarAlumno.add(jpModificarAlumno, BorderLayout.CENTER);
        jfModificarAlumno.pack();
        jfModificarAlumno.setLocationRelativeTo(null);
        jfModificarAlumno.setVisible(true);}
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jbBuscarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarMatriculaActionPerformed
        if ("".equals(jtfBuscarMatricula.getText())){
            actualizarGrilla();
        }
        else{
            Alumno alumno = new Alumno();
            alumno = alumnosDTO.extraer(Integer.parseInt(jtfBuscarMatricula.getText()));
            alumnos.clear();
            alumnos.add(alumno);
            GrillaAlumnos grilla = new GrillaAlumnos(alumnos);
            jtAlumnos.setModel(grilla);
        }
    }//GEN-LAST:event_jbBuscarMatriculaActionPerformed
    public static void actualizarGrilla(){
        alumnos = alumnosDTO.extraerTodo();
        GrillaAlumnos grilla = new GrillaAlumnos(alumnos);
        jtAlumnos.setModel(grilla);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private grillas.GrillaAlumnos grillaAlumnos1;
    private grillas.GrillaCargos grillaCargos1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbBuscarMatricula;
    private javax.swing.JButton jbCerrar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbNuevo;
    private static javax.swing.JTable jtAlumnos;
    private javax.swing.JTextField jtfBuscarMatricula;
    // End of variables declaration//GEN-END:variables
}
