/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uis;

import controladores.DocenteDTO;
import controladores.DocenteGradoDTO;
import grillas.GrillaDocentes;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import objetos.Docente;
import objetos.DocenteGrado;
import objetos.Grado;
import static uis.PreABMCargo.cargos;
import static uis.PreABMCargo.cargosDTO;
import static uis.PreABMGrado.gradosDTO;
import static uis.Principal.grados;
import static uis.Principal.docenteGrados;
/**
 *
 * @author ariel
 */
public class PreABMDocente extends javax.swing.JInternalFrame {

    /**
     * Creates new form PreABMDocente
     */
    
    static DocenteDTO docentesDTO = new DocenteDTO();
    public static DocenteGradoDTO docenteGradosDTO = new DocenteGradoDTO();
    static ArrayList<Docente> docentes = new ArrayList<>();
    DefaultComboBoxModel modeloGrados;

    public PreABMDocente() {
        cargos = cargosDTO.extraerTodo();
        grados = gradosDTO.extraerTodo();
        modeloGrados = new DefaultComboBoxModel(grados.toArray());
        initComponents();
        actualizarGrilla();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grillaCargos1 = new grillas.GrillaCargos();
        grillaAlumnos1 = new grillas.GrillaAlumnos();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDocentes = new javax.swing.JTable();
        jbCerrar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();
        jbBuscarLegajo = new javax.swing.JButton();
        jtfBuscarLegajo = new javax.swing.JTextField();
        jbAgregarGrado = new javax.swing.JButton();
        jcbAgregarGrado = new javax.swing.JComboBox<>();
        jbEliminarGrado = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jtDocentes.setModel(grillaAlumnos1);
        jScrollPane1.setViewportView(jtDocentes);

        jbCerrar.setText("Cerrar");
        jbCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrarActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jbBuscarLegajo.setText("Buscar por legajo");
        jbBuscarLegajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarLegajoActionPerformed(evt);
            }
        });

        jbAgregarGrado.setText("Agregar grado");
        jbAgregarGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarGradoActionPerformed(evt);
            }
        });

        jcbAgregarGrado.setModel(modeloGrados);

        jbEliminarGrado.setText("Eliminar grado");
        jbEliminarGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarGradoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jbNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbBuscarLegajo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfBuscarLegajo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCerrar))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jbAgregarGrado)
                .addGap(18, 18, 18)
                .addComponent(jcbAgregarGrado, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbEliminarGrado)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNuevo)
                    .addComponent(jbModificar)
                    .addComponent(jbEliminar)
                    .addComponent(jbCerrar)
                    .addComponent(jbBuscarLegajo)
                    .addComponent(jtfBuscarLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAgregarGrado)
                    .addComponent(jcbAgregarGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEliminarGrado)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("Comandos");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrarActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jbCerrarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        if (jtDocentes.getSelectedRow() == -1){JOptionPane.showMessageDialog(null, "Seleccione docente");}
        else{
            docenteGrados = docenteGradosDTO.extraerTodo();
            docenteGradosDTO.eliminar(docentes.get(jtDocentes.getSelectedRow()).getId());
            docentes = docentesDTO.extraerTodo();
            docentesDTO.eliminar(docentes.get(jtDocentes.getSelectedRow()).getId());
            actualizarGrilla();}
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        AltaDocente jpAltaDocente = new AltaDocente();      
        JFrame jfAltaDocente = new JFrame();
        jfAltaDocente.add(jpAltaDocente, BorderLayout.CENTER);
        jfAltaDocente.pack();
        jfAltaDocente.setLocationRelativeTo(null);
        jfAltaDocente.setVisible(true);
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        if (jtDocentes.getSelectedRow() == -1){JOptionPane.showMessageDialog(null, "Seleccione docente");}
        else{
        docentes = docentesDTO.extraerTodo();
        ModificarDocente jpModificarDocente = new ModificarDocente(docentes.get(jtDocentes.getSelectedRow()));  
        JFrame jfModificarDocente = new JFrame();
        jfModificarDocente.add(jpModificarDocente, BorderLayout.CENTER);
        jfModificarDocente.pack();
        jfModificarDocente.setLocationRelativeTo(null);
        jfModificarDocente.setVisible(true);}
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jbBuscarLegajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarLegajoActionPerformed
        if ("".equals(jtfBuscarLegajo.getText())){
            actualizarGrilla();
        }
        else{
            Docente docente = new Docente();
            docente = docentesDTO.extraer(Integer.parseInt(jtfBuscarLegajo.getText()));
            docentes.clear();
            docentes.add(docente);
            GrillaDocentes grilla = new GrillaDocentes(docentes);
            jtDocentes.setModel(grilla);
        }
    }//GEN-LAST:event_jbBuscarLegajoActionPerformed

    private void jbAgregarGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarGradoActionPerformed
        if (jtDocentes.getSelectedRow() == -1){JOptionPane.showMessageDialog(null, "Seleccione docente");}
        else{
            Grado grado = new Grado();
            DocenteGrado docenteGrado = new DocenteGrado();
            grado = (Grado) jcbAgregarGrado.getSelectedItem();
            docenteGrado.setIdGrado(grado.getId());
            docenteGrado.setIdDocente(docentes.get(jtDocentes.getSelectedRow()).getId());
            DocenteGradoDTO docenteGradoDTO = new DocenteGradoDTO();
            docenteGradoDTO.crear(docenteGrado);
            actualizarGrilla();
            
        }
    }//GEN-LAST:event_jbAgregarGradoActionPerformed

    private void jbEliminarGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarGradoActionPerformed
        if (jtDocentes.getSelectedRow() == -1){JOptionPane.showMessageDialog(null, "Seleccione docente");}
        else{
            Grado grado = new Grado();
            DocenteGrado docenteGrado = new DocenteGrado();
            grado = (Grado) jcbAgregarGrado.getSelectedItem();
            docenteGrado.setIdGrado(grado.getId());
            docenteGrado.setIdDocente(docentes.get(jtDocentes.getSelectedRow()).getId());
            DocenteGradoDTO docenteGradoDTO = new DocenteGradoDTO();
            docenteGradoDTO.eliminarG(docenteGrado.getIdGrado(), docenteGrado.getIdDocente());
            actualizarGrilla();
            
        }
    }//GEN-LAST:event_jbEliminarGradoActionPerformed
    public static void actualizarGrilla(){
        docentes = docentesDTO.extraerTodo();
        GrillaDocentes grilla = new GrillaDocentes(docentes);
        jtDocentes.setModel(grilla);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private grillas.GrillaAlumnos grillaAlumnos1;
    private grillas.GrillaCargos grillaCargos1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAgregarGrado;
    private javax.swing.JButton jbBuscarLegajo;
    private javax.swing.JButton jbCerrar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbEliminarGrado;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JComboBox<String> jcbAgregarGrado;
    private static javax.swing.JTable jtDocentes;
    private javax.swing.JTextField jtfBuscarLegajo;
    // End of variables declaration//GEN-END:variables
}
